["@types/node"]
  url = "https://github.com/DefinitelyTyped/DefinitelyTyped"
  version = 18.6.5
  license = MIT
["@types/prompts"]
  url = "https://github.com/DefinitelyTyped/DefinitelyTyped"
  version = 2.0.14
  license = MIT
["@types/yargs"]
  url = "https://github.com/DefinitelyTyped/DefinitelyTyped"
  version = 17.0.11
  license = MIT
[esbuild]
  url = "https://github.com/evanw/esbuild"
  version = 0.14.54
  license = MIT
[prettier]
  url = "prettier/prettier"
  version = 2.7.1
  license = MIT
[prettier-plugin-organize-imports]
  url = "simonhaenisch/prettier-plugin-organize-imports"
  version = 3.0.3
  license = MIT
[prompts]
  url = "terkelg/prompts"
  version = 2.4.2
  license = MIT
[typescript]
  url = "https://github.com/Microsoft/TypeScript"
  version = 4.7.4
  license = Apache-2.0
[yargs]
  url = "https://github.com/yargs/yargs"
  version = 17.5.1
  license = MIT