import { write } from '../helpers';
import { CreditJSON, CreditTypes } from '../types';

function writeCreditsMD(filePath: string, credits: CreditJSON[]) {
  const header =
    '# Acknowledgments and credits\n\nThese are open source libraries, tools, assets used in this project.';

  const footer =
    '---\nGenerated by [Acknowledgements](https://github.com/Clembs/acknowledgements).';

  const markdown = `${header}

| Name          | License |
| ------------- | ------- |
${credits
  .map((c) => {
    if (c.type === CreditTypes.Dependency) {
      return `| [${c.name}](${c.url}) | ${c.license} |`;
    } else {
      return `| [${c.name}](${c.url}) |   |`;
    }
  })
  .join('\n')}
    
${footer}
`;

  write(filePath, markdown);
}

export default writeCreditsMD;
